name: grocery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # REQUIRED FOR PHP API
  http: ^1.2.0

  # LOGIN, SIGNUP, PROFILE
  shared_preferences: ^2.3.2

  # IMAGE PICK & CROP
  image_picker: ^1.2.1
  image_cropper: ^11.0.0

  # URL LAUNCHER (for account deletion link)
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
